'use strict';
const $=id=>document.getElementById(id),canvas=$('scene'),gl=canvas.getContext('webgl2',{antialias:true,alpha:true,preserveDrawingBuffer:true});
if(!gl){$('solverState').textContent='WebGL 2 required';throw Error('This browser does not support WebGL 2. Enable hardware acceleration.');}
const state={speed:1,size:2.3,viscosity:.04,gravity:9.81,lighting:1,density:2500,rate:1,resolution:96,sphere:true,paused:false,mode:'speed',slice:false,lines:true,particles:true,vectors:false,domain:true};
let worker,field,mask,nx=96,ny=48,nz=48,dx=16/96,simTime=0,solverTime=0,solverSteps=0,metadata={},meshSource=null,parts=null,triangles=null,meshNormals=null,meshCount=0,frameId=0,lastFrame=0,fpsCount=0,fpsStart=0,dirtyLines=true,lastLineUpdate=0,streamCount=0,vectorCount=0,sliceCount=0,particleCount=0,ready=false,allowStep=false,initToken=0;
const camera={yaw:.24,pitch:.27,distance:18.8,target:[1,0,0]},v3={sub:(a,b)=>a.map((v,i)=>v-b[i]),dot:(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm:a=>{let n=Math.hypot(...a)||1;return a.map(v=>v/n);}};
// Object orientation is independent of the camera. Quaternions keep dragging
// continuous through all orientations; the numeric controls use Rz * Ry * Rx.
const orientation={q:[0,0,0,1],angles:[0,0,0],reference:'x',mode:'camera',pending:false,dragging:false,timer:null};
function quaternionProduct(a,b){return [a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]];}
function normalizeQuaternion(q){const length=Math.hypot(...q);return q.map(v=>v/length);}
function rotationMatrix(q=orientation.q){const [x,y,z,w]=q;return new Float32Array([1-2*(y*y+z*z),2*(x*y+z*w),2*(x*z-y*w),2*(x*y-z*w),1-2*(x*x+z*z),2*(y*z+x*w),2*(x*z+y*w),2*(y*z-x*w),1-2*(x*x+y*y)]);}
function rotatePoint(p,m=rotationMatrix()){return [m[0]*p[0]+m[3]*p[1]+m[6]*p[2],m[1]*p[0]+m[4]*p[1]+m[7]*p[2],m[2]*p[0]+m[5]*p[1]+m[8]*p[2]];}
function quaternionFromAngles(angles){const [x,y,z]=angles.map(a=>a*Math.PI/360),qx=[Math.sin(x),0,0,Math.cos(x)],qy=[0,Math.sin(y),0,Math.cos(y)],qz=[0,0,Math.sin(z),Math.cos(z)];return normalizeQuaternion(quaternionProduct(qz,quaternionProduct(qy,qx)));}
function anglesFromQuaternion(){const m=rotationMatrix(),y=Math.asin(Math.max(-1,Math.min(1,-m[2])));let x,z;if(Math.abs(Math.cos(y))>1e-5){x=Math.atan2(m[5],m[8]);z=Math.atan2(m[1],m[0]);}else{x=Math.atan2(-m[7],m[4]);z=0;}return [x,y,z].map(v=>v*180/Math.PI);}
function modelForward(){return rotatePoint(orientation.reference==='x'?[1,0,0]:orientation.reference==='y'?[0,1,0]:[0,0,1]);}
function syncOrientationControls(preserveEntry=false){
 for(let i=0;i<3;i++){const axis='XYZ'[i],v=Math.round(orientation.angles[i]*10)/10;$('rotation'+axis).value=v;if(!preserveEntry||document.activeElement!==$('angle'+axis))$('angle'+axis).value=v;}
 const direction=modelForward();document.querySelectorAll('[data-align]').forEach(b=>{const k='xyz'.indexOf(b.dataset.align),active=direction[k]>1-1e-5;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active));});
 $('rotationHelp').textContent=state.sphere?'Choose Rotate object, then drag the scene. A sphere looks the same at every angle.':'Choose Rotate object, then drag the scene. Angles also accept exact values.';
}
function setDragMode(mode){orientation.mode=mode;for(const key of ['camera','object']){const active=mode===key;$(key+'Drag').classList.toggle('active',active);$(key+'Drag').setAttribute('aria-pressed',String(active));}document.body.classList.toggle('rotate-object',mode==='object');document.querySelector('.orbit-hint').innerHTML=(mode==='object'?'Drag to rotate object':'Drag to orbit')+' · Scroll to zoom<br><span>Shift + drag to pan · Space to freeze</span>';canvas.setAttribute('aria-label',mode==='object'?'Drag to rotate the object in the fluid field; release to recalculate flow. Scroll to zoom.':'Drag to orbit the camera around the fluid field. Scroll to zoom.');}
function beginOrientationPreview(){
 clearTimeout(orientation.timer);clearTimeout(initTimer);
 if(orientation.pending)return;
 orientation.pending=true;initToken++;if(worker){worker.terminate();worker=null;}
 ready=false;field=null;curlField=null;mask=null;streamCount=vectorCount=sliceCount=0;dirtyLines=false;simTime=solverTime=solverSteps=0;metadata={};
 $('solverState').textContent='Orienting object · release to solve';$('development').textContent='Orientation preview';$('stepsRate').textContent='— steps/s';$('frozenHint').textContent='Release to recalculate flow';$('playBtn').disabled=true;$('stepBtn').disabled=true;
}
function previewOrientation(q,angles=null,preserveEntry=false){beginOrientationPreview();orientation.q=normalizeQuaternion(q);orientation.angles=angles||anglesFromQuaternion();syncOrientationControls(preserveEntry);}
function commitOrientation(){clearTimeout(orientation.timer);if(orientation.pending)initSolver();}
function resetOrientationState(){orientation.q=[0,0,0,1];orientation.angles=[0,0,0];syncOrientationControls();}
function alignObject(axis){const from=orientation.reference==='x'?[1,0,0]:orientation.reference==='y'?[0,1,0]:[0,0,1],to=axis==='x'?[1,0,0]:axis==='y'?[0,1,0]:[0,0,1];previewOrientation([...v3.cross(from,to),1+v3.dot(from,to)]);commitOrientation();}
function dragObject(dx,dy){const distance=Math.hypot(dx,dy);if(!distance)return;const right=[Math.cos(camera.yaw),0,-Math.sin(camera.yaw)],up=[-Math.sin(camera.yaw)*Math.sin(camera.pitch),Math.cos(camera.pitch),-Math.cos(camera.yaw)*Math.sin(camera.pitch)],axis=v3.norm(right.map((v,i)=>v*dy+up[i]*dx)),half=distance*.004,dq=[...axis.map(v=>v*Math.sin(half)),Math.cos(half)];previewOrientation(quaternionProduct(dq,orientation.q));}
function bindOrientationControls(){
 $('cameraDrag').onclick=()=>setDragMode('camera');$('objectDrag').onclick=()=>setDragMode('object');
 $('resetOrientation').onclick=()=>{previewOrientation([0,0,0,1],[0,0,0]);commitOrientation();};
 $('modelAxis').onchange=()=>{orientation.reference=$('modelAxis').value;syncOrientationControls();};
 document.querySelectorAll('[data-align]').forEach(b=>b.onclick=()=>alignObject(b.dataset.align));
 for(let i=0;i<3;i++){
  const axis='XYZ'[i],slider=$('rotation'+axis),number=$('angle'+axis);
  const edit=e=>{if(e.target.value.trim()==='')return;const n=Number(e.target.value);if(!Number.isFinite(n))return;const angles=orientation.angles.slice();angles[i]=Math.max(-180,Math.min(180,n));previewOrientation(quaternionFromAngles(angles),angles,e.target===number);if(!orientation.dragging)orientation.timer=setTimeout(commitOrientation,350);};
  slider.oninput=edit;number.oninput=edit;
  slider.addEventListener('pointerdown',()=>{orientation.dragging=true;});
  for(const event of ['pointerup','pointercancel','lostpointercapture'])slider.addEventListener(event,()=>{orientation.dragging=false;commitOrientation();});
  slider.onchange=()=>{if(!orientation.dragging)commitOrientation();};
  number.onchange=()=>{syncOrientationControls();commitOrientation();};
 }
 syncOrientationControls();
}

function mul(a,b){let o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function viewMatrix(eye,target){const z=v3.norm(v3.sub(eye,target)),x=v3.norm(v3.cross([0,1,0],z)),y=v3.cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-v3.dot(x,eye),-v3.dot(y,eye),-v3.dot(z,eye),1]);}
function projection(aspect){const f=1/Math.tan(.57/2),near=.1,far=150;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0]);}
function program(vs,fs){function compile(type,src){const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(sh));return sh;}const p=gl.createProgram();gl.attachShader(p,compile(gl.VERTEX_SHADER,vs));gl.attachShader(p,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
const lineProgram=program(`#version 300 es
precision highp float;layout(location=0) in vec3 pos;layout(location=1) in vec4 color;uniform mat4 vp;uniform float pointSize;out vec4 c;void main(){gl_Position=vp*vec4(pos,1.);c=color;gl_PointSize=clamp(pointSize*110./gl_Position.w,1.,5.);}`,`#version 300 es
precision highp float;in vec4 c;uniform bool points;out vec4 frag;void main(){float a=c.a;if(points){float r=length(gl_PointCoord-.5)*2.;if(r>1.)discard;a*=smoothstep(1.,.12,r);}frag=vec4(c.rgb,a);}`);
const meshProgram=program(`#version 300 es
precision highp float;layout(location=0) in vec3 pos;layout(location=1) in vec3 normal;uniform mat4 vp;uniform mat3 objectRotation;out vec3 p;out vec3 n;void main(){p=objectRotation*pos;n=objectRotation*normal;gl_Position=vp*vec4(p,1.);}`,`#version 300 es
precision highp float;precision highp sampler3D;in vec3 p;in vec3 n;uniform vec3 eye;uniform float lightLevel;uniform sampler3D flow;uniform vec3 grid;uniform float cell;uniform float speed;uniform int mode;uniform float gravity;out vec4 frag;
vec4 sampleFlow(vec3 p0){vec3 c=(p0+vec3(6,4,4))/cell-.5;ivec3 i=ivec3(floor(c));vec3 f=fract(c);vec4 a=vec4(0);for(int z=0;z<2;z++)for(int y=0;y<2;y++)for(int x=0;x<2;x++){vec3 w=mix(1.-f,f,vec3(x,y,z));a+=texelFetch(flow,clamp(i+ivec3(x,y,z),ivec3(0),ivec3(grid)-1),0)*w.x*w.y*w.z;}return a;}
vec3 ramp(float t){t=clamp(t,0.,1.);vec3 a=vec3(.14,.23,.76),b=vec3(.11,.65,.87),c=vec3(.26,.87,.77),d=vec3(.91,.90,.49),e=vec3(.98,.55,.32);if(t<.25)return mix(a,b,t*4.);if(t<.5)return mix(b,c,(t-.25)*4.);if(t<.75)return mix(c,d,(t-.5)*4.);return mix(d,e,(t-.75)*4.);}
void main(){vec3 N=normalize(n);if(!gl_FrontFacing)N=-N;vec3 V=normalize(eye-p),L=normalize(vec3(-.4,.85,.55)),H=normalize(V+L);float ndl=max(dot(N,L),0.),ndv=max(dot(N,V),.001),ndh=max(dot(N,H),0.);vec3 base=vec3(.31,.40,.45);vec4 f=sampleFlow(p+N*cell*.9);if(mode==1)base=ramp((f.w+1.4)/2.8)*.75;if(mode==2){float pressure=.5*1.225*speed*speed*f.w-1.225*gravity*p.y;float range=max(.5*1.225*speed*speed*1.4,1.225*gravity*4.);base=ramp(.5+.5*pressure/range)*.75;}if(mode==3)base=ramp(length(f.xyz)/speed/1.5)*.7;
float fres=pow(1.-ndv,5.);float spec=pow(ndh,90.)*.72+pow(ndh,12.)*.1;float rim=pow(1.-ndv,3.);vec3 col=base*(.18+.7*ndl)*lightLevel;col+=vec3(.95,.99,1.)*spec*lightLevel;col+=vec3(.32,.69,.77)*rim*.25;col+=vec3(.26,.34,.42)*max(N.y,0.)*.32;col+=vec3(.6,.86,.92)*fres*.24;col=pow(col,vec3(1./2.2));frag=vec4(col,1.);}`);
const floorProgram=program(`#version 300 es
precision highp float;layout(location=0) in vec3 pos;uniform mat4 vp;out vec3 p;void main(){p=pos;gl_Position=vp*vec4(pos,1.);}`,`#version 300 es
precision highp float;in vec3 p;uniform float radius;uniform float lightLevel;out vec4 frag;void main(){vec2 g=abs(fract(p.xz*.5-.5)-.5)/fwidth(p.xz*.5);float line=1.-min(min(g.x,g.y),1.);float fade=exp(-length(p.xz-vec2(1.,0.))*.08);float shadow=1.-.68*exp(-dot(p.xz,p.xz)/(radius*radius*1.7));vec3 color=mix(vec3(.048,.078,.104),vec3(.10,.17,.20),line*.25)*shadow;frag=vec4(color*lightLevel,fade*.8);}`);
const flowTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_3D,flowTexture);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_3D,gl.TEXTURE_WRAP_R,gl.CLAMP_TO_EDGE);gl.texImage3D(gl.TEXTURE_3D,0,gl.RGBA32F,nx,ny,nz,0,gl.RGBA,gl.FLOAT,null);
function buffer(){return gl.createBuffer();}const meshBuffer=buffer(),lineBuffer=buffer(),particleBuffer=buffer(),vectorBuffer=buffer(),sliceBuffer=buffer(),floorBuffer=buffer(),domainBuffer=buffer();
function upload(b,a){gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,a,gl.DYNAMIC_DRAW);}
upload(floorBuffer,new Float32Array([-9,-4.06,-7,14,-4.06,-7,-9,-4.06,7,-9,-4.06,7,14,-4.06,-7,14,-4.06,7]));
function sphereGeometry(radius){let t=[],normals=[];const lat=64,lon=96;function p(a,b){return [Math.cos(b)*Math.sin(a),Math.cos(a),Math.sin(b)*Math.sin(a)];}for(let j=0;j<lat;j++)for(let i=0;i<lon;i++){const a=j*Math.PI/lat,b=i*2*Math.PI/lon,A=(j+1)*Math.PI/lat,B=(i+1)*2*Math.PI/lon,ps=[p(a,b),p(A,B),p(A,b),p(a,b),p(a,B),p(A,B)];for(const q of ps){t.push(...q.map(v=>v*radius));normals.push(...q);}}return [new Float32Array(t),new Float32Array(normals)];}
function buildMesh(){
 if(state.sphere)[triangles,meshNormals]=sphereGeometry(state.size/2);
 else{let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<meshSource.length;i++) {min[i%3]=Math.min(min[i%3],meshSource[i]);max[i%3]=Math.max(max[i%3],meshSource[i]);}const scale=state.size/Math.max(...max.map((v,i)=>v-min[i]));triangles=new Float32Array(meshSource.length);for(let i=0;i<triangles.length;i++)triangles[i]=(meshSource[i]-(max[i%3]+min[i%3])/2)*scale;meshNormals=new Float32Array(triangles.length);for(let i=0;i<triangles.length;i+=9){const A=Array.from(triangles.slice(i,i+3)),B=Array.from(triangles.slice(i+3,i+6)),C=Array.from(triangles.slice(i+6,i+9)),N=v3.norm(v3.cross(v3.sub(B,A),v3.sub(C,A)));for(let j=0;j<3;j++)meshNormals.set(N,i+j*3);}}
 const a=new Float32Array(triangles.length*2);for(let i=0;i<triangles.length/3;i++){a.set(triangles.subarray(i*3,i*3+3),i*6);a.set(meshNormals.subarray(i*3,i*3+3),i*6+3);}meshCount=triangles.length/3;upload(meshBuffer,a);
 // Normalize before rotation so orientation never changes the physical size.
 const r=rotationMatrix();for(let i=0;i<triangles.length;i+=3){const x=triangles[i],y=triangles[i+1],z=triangles[i+2];triangles[i]=r[0]*x+r[3]*y+r[6]*z;triangles[i+1]=r[1]*x+r[4]*y+r[7]*z;triangles[i+2]=r[2]*x+r[5]*y+r[8]*z;}
}
function initSolver(){
 clearTimeout(initTimer);clearTimeout(orientation.timer);orientation.pending=false;orientation.dragging=false;$('playBtn').disabled=false;$('stepBtn').disabled=false;$('frozenHint').textContent=state.paused?'Time frozen · camera is free':'';
 initToken++;const token=initToken;const solvedRotation=orientation.q.slice();ready=false;field=null;curlField=null;mask=null;streamCount=vectorCount=sliceCount=0;solverTime=simTime=solverSteps=0;metadata={};$('solverState').textContent='Building solid boundary…';$('development').textContent='Initializing';
 if(worker)worker.terminate();buildMesh();resetParticles();worker=new Worker('solver.js');
 worker.onerror=e=>toast('Solver error: '+e.message,12000);
 worker.onmessage=e=>{if(token!==initToken)return;const m=e.data;if(m.type==='ready'){({nx,ny,nz,dx,mask}=m);metadata=m;metadata.objectRotation=solvedRotation;ready=true;$('gridValue').textContent=`${nx} × ${ny} × ${nz}`;$('reValue').textContent=m.re.toFixed(0);$('effectiveViscosity').textContent=m.nu.toFixed(3)+' m²/s';$('solverState').textContent=state.paused?'Frozen · orbit freely':'Developing flow';gl.bindTexture(gl.TEXTURE_3D,flowTexture);gl.texImage3D(gl.TEXTURE_3D,0,gl.RGBA32F,nx,ny,nz,0,gl.RGBA,gl.FLOAT,null);updateNumerics();if(m.nu>state.viscosity*1.01)toast(`Stability limit: effective viscosity ${m.nu.toFixed(3)} m²/s (Re ${m.re.toFixed(0)}).`,6500);}
 else if(m.type==='field'){if(state.paused&&!allowStep&&field&&m.reason!=='pause'&&m.reason!=='step')return;field=m.field;updateCurl();solverTime=m.time;solverSteps=m.steps;metadata.diagnostics=m.diagnostics;metadata.rate=m.rate;dirtyLines=true;gl.bindTexture(gl.TEXTURE_3D,flowTexture);gl.texSubImage3D(gl.TEXTURE_3D,0,0,0,0,nx,ny,nz,gl.RGBA,gl.FLOAT,field);if(m.reason==='pause'||m.reason==='step'){const advance=Math.max(0,solverTime-simTime);if(advance>0)updateParticles(Math.min(advance,.1));simTime=solverTime;allowStep=false;}updateReadouts();}
 else if(m.type==='warning')toast(m.text,9000);else if(m.type==='unstable'){setPaused(true);toast(m.text,15000);}};
 worker.postMessage({type:'init',paused:state.paused,params:{speed:state.speed,size:state.size,viscosity:state.viscosity,rate:state.rate,resolution:state.resolution,sphere:state.sphere,triangles:state.sphere?null:triangles,parts}});
}
function updateNumerics(){if(!metadata.nu)return;$('numerics').textContent=`Current grid: ${nx} × ${ny} × ${nz}; cell size ${dx.toFixed(3)} m. Effective viscosity: ${metadata.nu.toFixed(4)} m²/s. Reynolds number: ${metadata.re.toFixed(1)}. Relaxation time: ${metadata.tau.toFixed(4)}. Lattice inlet Mach: 0.130. ${metadata.solidCount.toLocaleString()} solid cells.`;}
function updateReadouts(){const crossing=solverTime*state.speed/state.size;$('development').textContent=crossing<1?'Starting':crossing<6?`${crossing.toFixed(1)} flow-throughs`:`${crossing.toFixed(1)} flow-throughs`;$('solverState').textContent=state.paused?'Frozen · orbit freely':crossing<5?'Developing flow':'Flow evolving';$('stepsRate').textContent=`${(metadata.rate||0).toFixed(0)} steps/s`;}
function toast(text,ms=5000){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',ms);}
let curlField=null;
function updateCurl(){
 curlField=null;if(state.mode!=='vorticity'||!field)return;curlField=new Float32Array(nx*ny*nz);
 for(let z=1;z<nz-1;z++)for(let y=1;y<ny-1;y++)for(let x=1;x<nx-1;x++){
  const i=x+nx*(y+ny*z),k=i*4,a=nx*4,b=nx*ny*4;
  if(mask&&mask[i]===3)continue;
  const wx=(field[k+a+2]-field[k-a+2]-field[k+b+1]+field[k-b+1])/(2*dx);
  const wy=(field[k+b]-field[k-b]-field[k+4+2]+field[k-4+2])/(2*dx);
  const wz=(field[k+4+1]-field[k-4+1]-field[k+a]+field[k-a])/(2*dx);
  curlField[i]=Math.hypot(wx,wy,wz);
 }
}
const sampleOut=new Float32Array(5);
function sample(x,y,z,out=sampleOut){out.fill(0);if(!field||x< -5.95||x>9.95||Math.abs(y)>3.95||Math.abs(z)>3.95)return out;let xx=(x+6)/dx-.5,yy=(y+4)/dx-.5,zz=(z+4)/dx-.5,ix=Math.max(0,Math.min(nx-2,Math.floor(xx))),iy=Math.max(0,Math.min(ny-2,Math.floor(yy))),iz=Math.max(0,Math.min(nz-2,Math.floor(zz))),a=Math.max(0,Math.min(1,xx-ix)),b=Math.max(0,Math.min(1,yy-iy)),c=Math.max(0,Math.min(1,zz-iz));for(let dz=0;dz<2;dz++)for(let dy=0;dy<2;dy++)for(let dxx=0;dxx<2;dxx++){const i=4*(ix+dxx+nx*(iy+dy+ny*(iz+dz))),w=(dxx?a:1-a)*(dy?b:1-b)*(dz?c:1-c);out[0]+=field[i]*w;out[1]+=field[i+1]*w;out[2]+=field[i+2]*w;out[3]+=field[i+3]*w;if(curlField)out[4]+=curlField[i/4]*w;}return out;}
function inside(x,y,z){if(!mask)return false;if(state.sphere)return Math.hypot(x,y,z)<state.size/2+dx*.13;const ix=Math.floor((x+6)/dx),iy=Math.floor((y+4)/dx),iz=Math.floor((z+4)/dx);return ix<0||ix>=nx||iy<0||iy>=ny||iz<0||iz>=nz||mask[ix+nx*(iy+ny*iz)]===3;}
const colors=[[.14,.23,.76],[.11,.65,.87],[.26,.87,.77],[.91,.90,.49],[.98,.55,.32]];
function ramp(t){t=Math.max(0,Math.min(.9999,t))*4;const i=Math.floor(t),f=t-i;return colors[i].map((v,j)=>v+(colors[i+1][j]-v)*f);}
function curl(x,y,z){let h=dx*1.2,a=Array.from(sample(x,y+h,z)),b=Array.from(sample(x,y-h,z)),c=Array.from(sample(x,y,z+h)),d=Array.from(sample(x,y,z-h)),e=Array.from(sample(x+h,y,z)),f=Array.from(sample(x-h,y,z));return Math.hypot((a[2]-b[2]-c[1]+d[1])/(2*h),(c[0]-d[0]-e[2]+f[2])/(2*h),(e[1]-f[1]-a[0]+b[0])/(2*h));}
function scalar(x,y,z,s){if(state.mode==='pressure')return (s[3]+1.4)/2.8;if(state.mode==='total'){const r=Math.max(.5*1.225*state.speed**2*1.4,1.225*state.gravity*4);return .5+.5*(.5*1.225*state.speed**2*s[3]-1.225*state.gravity*y)/r;}if(state.mode==='vorticity')return (s[4]||0)/(state.speed/state.size*5);return Math.hypot(s[0],s[1],s[2])/(state.speed*1.5);}
function vert(a,p,c,alpha){a.push(p[0],p[1],p[2],c[0],c[1],c[2],alpha);}
function trace(a,seed,steps,alpha,direction=1){let p=seed.slice();for(let k=0;k<steps;k++){if(p[0]<-5.85||p[0]>9.3||Math.abs(p[1])>3.5||Math.abs(p[2])>3.5||inside(...p))break;const s=Array.from(sample(...p)),vel=Math.hypot(s[0],s[1],s[2]);if(vel<.003*state.speed)break;const h=.105*direction/vel;const mid=[p[0]+s[0]*h/2,p[1]+s[1]*h/2,p[2]+s[2]*h/2],m=Array.from(sample(...mid)),q=[p[0]+m[0]*h,p[1]+m[1]*h,p[2]+m[2]*h];if(inside(...mid)||inside(...q))break;const c=ramp(scalar(...p,s)),fade=Math.min(1,k/8,(steps-k)/10);vert(a,p,c,alpha*fade);vert(a,q,c,alpha*fade);p=q;}}
function updateLines(){if(!field)return;const a=[];
 // Three-dimensional rake, denser around the object, with a separate wake rake.
 for(let zi=-2;zi<=2;zi++)for(let yi=-8;yi<=8;yi++)trace(a,[-5.8,yi*.28,zi*.65],175,zi===0?.39:.075);
 for(let i=0;i<4;i++){const ang=i*Math.PI*2/4;for(let r of [.28,.65]){const seed=[state.size*.72,r*Math.cos(ang),r*Math.sin(ang)];trace(a,seed,85,.18,1);trace(a,seed,60,.11,-1);}}
 streamCount=a.length/7;upload(lineBuffer,new Float32Array(a));dirtyLines=false;updateVectors();updateSlice();}
function updateVectors(){const a=[];if(state.vectors)for(let x=-5;x<8.5;x+=.7)for(let y=-2.8;y<=2.8;y+=.55){const p=[x,y,0];if(inside(...p))continue;const s=Array.from(sample(...p)),v=s.slice(0,3),mag=Math.hypot(...v);if(mag<.02)continue;let len=.36*Math.min(1.5,mag/state.speed),unit=v.map(q=>q/mag),q=p.map((v,i)=>v+unit[i]*len),c=ramp(scalar(...p,s));vert(a,p,c,.68);vert(a,q,c,.68);let cross=v3.norm(v3.cross(unit,[0,0,1]));for(let side of [-1,1]){vert(a,q,c,.68);vert(a,q.map((v,i)=>v-unit[i]*.09+cross[i]*side*.047),c,.68);}}vectorCount=a.length/7;upload(vectorBuffer,new Float32Array(a));}
function updateSlice(){const a=[];if(state.slice&&field)for(let y=2;y<ny-2;y++)for(let x=2;x<nx-3;x++){const xx=-6+(x+.5)*dx,yy=-4+(y+.5)*dx;if(inside(xx,yy,0))continue;const c=ramp(scalar(xx,yy,0,Array.from(sample(xx,yy,0))));for(const p of [[xx-dx/2,yy-dx/2,0],[xx+dx/2,yy-dx/2,0],[xx-dx/2,yy+dx/2,0],[xx-dx/2,yy+dx/2,0],[xx+dx/2,yy-dx/2,0],[xx+dx/2,yy+dx/2,0]])vert(a,p,c,.28);}sliceCount=a.length/7;upload(sliceBuffer,new Float32Array(a));}
let particles=[],particleData=new Float32Array(10000*2*7),randSeed=7321;
function random(){randSeed=(Math.imul(1664525,randSeed)+1013904223)>>>0;return randSeed/4294967296;}
function newParticle(initial=false){let p;for(let i=0;i<12;i++){const focus=random()<.75;p=[initial?-5.7+random()*14.5:-5.7,(random()-.5)*(focus?4.8:6.7),(random()-.5)*(focus?3.8:6.7),random()*20];if(!inside(p[0],p[1],p[2]))break;}return p;}
function resetParticles(){particles=[];randSeed=7321;for(let i=0;i<10000;i++)particles.push(newParticle(true));}
function updateParticles(dt){let at=0;for(let i=0;i<state.density;i++){let p=particles[i];const s=Array.from(sample(p[0],p[1],p[2])),mag=Math.hypot(s[0],s[1],s[2]);if(dt>0){const mid=[p[0]+s[0]*dt/2,p[1]+s[1]*dt/2,p[2]+s[2]*dt/2],m=Array.from(sample(...mid)),q=[p[0]+m[0]*dt,p[1]+m[1]*dt,p[2]+m[2]*dt];p[3]+=dt;if(q[0]>9.2||q[0]<-5.85||Math.abs(q[1])>3.5||Math.abs(q[2])>3.5||inside(...q)||inside(...mid)||p[3]>45){p=particles[i]=newParticle(false);}else{p[0]=q[0];p[1]=q[1];p[2]=q[2];}}
 const c=ramp(scalar(p[0],p[1],p[2],s));const length=.075/Math.max(.05,mag);for(let k=0;k<2;k++){particleData[at++]=p[0]-s[0]*length*k;particleData[at++]=p[1]-s[1]*length*k;particleData[at++]=p[2]-s[2]*length*k;particleData[at++]=c[0];particleData[at++]=c[1];particleData[at++]=c[2];particleData[at++]=k?.06:.85;}}
 particleCount=at/7;upload(particleBuffer,particleData.subarray(0,at));}
function buildDomain(){let a=[];const c=[.32,.50,.58];const min=[-6,-4,-4],max=[10,4,4];for(let axis=0;axis<3;axis++)for(let j=0;j<4;j++){let p=[0,0,0],q=[0,0,0];for(let k=0;k<3;k++)if(k===axis){p[k]=min[k];q[k]=max[k];}else{const bit=k<axis?k:k-1;p[k]=q[k]=(j>>bit)&1?max[k]:min[k];}vert(a,p,c,.18);vert(a,q,c,.18);}upload(domainBuffer,new Float32Array(a));}
function drawLines(b,count,vp,primitive=gl.LINES,points=false){if(!count)return;gl.useProgram(lineProgram);gl.uniformMatrix4fv(gl.getUniformLocation(lineProgram,'vp'),false,vp);gl.uniform1f(gl.getUniformLocation(lineProgram,'pointSize'),.36*devicePixelRatio);gl.uniform1i(gl.getUniformLocation(lineProgram,'points'),points);gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.enableVertexAttribArray(0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(0,3,gl.FLOAT,false,28,0);gl.vertexAttribPointer(1,4,gl.FLOAT,false,28,12);gl.drawArrays(primitive,0,count);}
function render(ts){frameId=requestAnimationFrame(render);const realDt=Math.min(.05,(ts-lastFrame)/1000||0);lastFrame=ts;const rect=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,1.7),w=Math.floor(rect.width*dpr),h=Math.floor(rect.height*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(true);
 const eye=[camera.target[0]+Math.sin(camera.yaw)*Math.cos(camera.pitch)*camera.distance,camera.target[1]+Math.sin(camera.pitch)*camera.distance,camera.target[2]+Math.cos(camera.yaw)*Math.cos(camera.pitch)*camera.distance],vp=mul(projection(w/h),viewMatrix(eye,camera.target));
 gl.useProgram(floorProgram);gl.uniformMatrix4fv(gl.getUniformLocation(floorProgram,'vp'),false,vp);gl.uniform1f(gl.getUniformLocation(floorProgram,'radius'),state.size/2);gl.uniform1f(gl.getUniformLocation(floorProgram,'lightLevel'),.65+.35*state.lighting);gl.bindBuffer(gl.ARRAY_BUFFER,floorBuffer);gl.enableVertexAttribArray(0);gl.disableVertexAttribArray(1);gl.vertexAttribPointer(0,3,gl.FLOAT,false,12,0);gl.drawArrays(gl.TRIANGLES,0,6);
 gl.useProgram(meshProgram);gl.uniformMatrix3fv(gl.getUniformLocation(meshProgram,'objectRotation'),false,rotationMatrix());gl.uniformMatrix4fv(gl.getUniformLocation(meshProgram,'vp'),false,vp);gl.uniform3fv(gl.getUniformLocation(meshProgram,'eye'),eye);gl.uniform1f(gl.getUniformLocation(meshProgram,'lightLevel'),state.lighting);gl.uniform1f(gl.getUniformLocation(meshProgram,'speed'),state.speed);gl.uniform1f(gl.getUniformLocation(meshProgram,'cell'),dx);gl.uniform3f(gl.getUniformLocation(meshProgram,'grid'),nx,ny,nz);gl.uniform1f(gl.getUniformLocation(meshProgram,'gravity'),state.gravity);gl.uniform1i(gl.getUniformLocation(meshProgram,'mode'),!field?0:state.mode==='pressure'?1:state.mode==='total'?2:0);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_3D,flowTexture);gl.uniform1i(gl.getUniformLocation(meshProgram,'flow'),0);gl.bindBuffer(gl.ARRAY_BUFFER,meshBuffer);gl.enableVertexAttribArray(0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(0,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(1,3,gl.FLOAT,false,24,12);gl.drawArrays(gl.TRIANGLES,0,meshCount);
 gl.depthMask(false);if(state.domain)drawLines(domainBuffer,24,vp);if(dirtyLines&&ts-lastLineUpdate>420){updateLines();lastLineUpdate=ts;}if(state.slice)drawLines(sliceBuffer,sliceCount,vp,gl.TRIANGLES);if(state.lines)drawLines(lineBuffer,streamCount,vp);if(state.vectors)drawLines(vectorBuffer,vectorCount,vp);
 let dt=0;if(!state.paused&&field){dt=Math.min(realDt*state.rate,Math.max(0,solverTime-simTime));simTime+=dt;}$('simTime').textContent=simTime.toFixed(2);if(field){updateParticles(dt);if(state.particles){drawLines(particleBuffer,particleCount,vp);drawLines(particleBuffer,particleCount,vp,gl.POINTS,true);}}
 gl.depthMask(true);fpsCount++;if(ts-fpsStart>1000){$('fps').textContent=`${Math.round(fpsCount*1000/(ts-fpsStart))} fps`;fpsCount=0;fpsStart=ts;}
}
function setPaused(value){if(orientation.pending)return;state.paused=value;document.body.classList.toggle('frozen',value);$('playBtn').innerHTML=value?'▶ <span>Resume</span>':'Ⅱ <span>Freeze</span>';$('playBtn').setAttribute('aria-label',value?'Resume simulation':'Pause simulation');$('frozenHint').textContent=value?'Time frozen · camera is free':'';if(worker)worker.postMessage({type:'pause',value});updateReadouts();}
function setView(view){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='perspective'){camera.yaw=.24;camera.pitch=.27;camera.distance=18.8;camera.target=[1,0,0];}if(view==='side'){camera.yaw=0;camera.pitch=0;camera.distance=19;camera.target=[1,0,0];}if(view==='top'){camera.yaw=0;camera.pitch=Math.PI/2-.001;camera.distance=19;camera.target=[1,0,0];}if(view==='front'){camera.yaw=-Math.PI/2;camera.pitch=.01;camera.distance=16;camera.target=[0,0,0];}}
let pointer=null;
canvas.addEventListener('pointerdown',e=>{if(pointer)return;canvas.setPointerCapture(e.pointerId);pointer={id:e.pointerId,x:e.clientX,y:e.clientY,shift:e.shiftKey||e.button===2,object:orientation.mode==='object'&&!e.shiftKey&&e.button!==2};if(pointer.object)orientation.dragging=true;});
canvas.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;const x=e.clientX-pointer.x,y=e.clientY-pointer.y;if(pointer.shift){camera.target[0]-=x*.012*Math.cos(camera.yaw);camera.target[2]+=x*.012*Math.sin(camera.yaw);camera.target[1]+=y*.012;}else if(pointer.object){dragObject(x,y);}else{camera.yaw-=x*.006;camera.pitch=Math.max(-1.56,Math.min(1.56,camera.pitch+y*.006));}pointer.x=e.clientX;pointer.y=e.clientY;});
function endSceneDrag(e){if(!pointer||e.pointerId!==pointer.id)return;const object=pointer.object;pointer=null;orientation.dragging=false;if(object)commitOrientation();}
canvas.addEventListener('pointerup',endSceneDrag);canvas.addEventListener('pointercancel',endSceneDrag);canvas.addEventListener('lostpointercapture',endSceneDrag);canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('wheel',e=>{e.preventDefault();camera.distance=Math.max(4,Math.min(45,camera.distance*Math.exp(e.deltaY*.001)));},{passive:false});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('playBtn').onclick=()=>setPaused(!state.paused);$('stepBtn').onclick=()=>{if(orientation.pending||!worker)return;if(!state.paused)setPaused(true);allowStep=true;worker.postMessage({type:'step'});};$('restartBtn').onclick=()=>initSolver();document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','SELECT','BUTTON','TEXTAREA'].includes(e.target.tagName)&&!$('about').open){e.preventDefault();setPaused(!state.paused);}});
let initTimer;const physical=new Set(['speed','size','viscosity']);
for(const [id,format] of Object.entries({speed:v=>v.toFixed(2)+' m/s',size:v=>v.toFixed(2)+' m',viscosity:v=>v.toFixed(3)+' m²/s',gravity:v=>v.toFixed(2)+' m/s²',density:v=>v.toLocaleString(),lighting:v=>v+'%',rate:v=>v+'×'})){$(id).oninput=()=>{let value=+$(id).value;state[id]=id==='lighting'?value/100:value;$(id+'Value').textContent=format(value);if(physical.has(id)){updateLegend();clearTimeout(initTimer);initTimer=setTimeout(initSolver,350);}if(id==='rate'&&worker)worker.postMessage({type:'rate',value});if(id==='gravity'){dirtyLines=true;updateLegend();}};}
$('quality').onchange=()=>{state.resolution=+$('quality').value;initSolver();};$('colorMode').onchange=()=>{state.mode=$('colorMode').value;updateCurl();dirtyLines=true;updateLegend();};$('sliceMode').onchange=()=>{state.slice=$('sliceMode').value==='on';dirtyLines=true;};for(const [id,key] of Object.entries({showLines:'lines',showParticles:'particles',showVectors:'vectors',showDomain:'domain'}))$(id).onchange=()=>{state[key]=$(id).checked;dirtyLines=true;};
function updateLegend(){let min=0,max=state.speed*1.5,title='VELOCITY · m/s';if(state.mode==='pressure'){max=.5*1.225*state.speed**2*1.4;min=-max;title='STATIC PRESSURE · Pa';}else if(state.mode==='total'){max=Math.max(.5*1.225*state.speed**2*1.4,1.225*state.gravity*4);min=-max;title='STATIC + GRAVITY · Pa';}else if(state.mode==='vorticity'){max=state.speed/state.size*5;title='VORTICITY · 1/s';}$('legendTitle').textContent=title;$('legendMin').textContent=min.toFixed(2);$('legendMid').textContent=((min+max)/2).toFixed(2);$('legendMax').textContent=max.toFixed(2);}
$('aboutBtn').onclick=()=>{updateNumerics();$('about').showModal();};$('closeAbout').onclick=()=>$('about').close();$('about').onclick=e=>{if(e.target===$('about'))$('about').close();};$('captureBtn').onclick=()=>{const a=document.createElement('a');a.download=`flow-lab-${simTime.toFixed(2)}s.png`;a.href=canvas.toDataURL('image/png');a.click();};
function parseOBJ(text){const v=[],t=[];for(const line of text.split(/\r?\n/)){const p=line.trim().split(/\s+/);if(p[0]==='v'){const q=p.slice(1,4).map(Number);if(q.length!==3||q.some(x=>!Number.isFinite(x)))throw Error('Invalid OBJ vertex.');v.push(q);}if(p[0]==='f'){const f=p.slice(1).map(s=>{const idx=parseInt(s.split('/')[0]);return idx<0?v.length+idx:idx-1;});for(let i=1;i<f.length-1;i++)for(const j of [f[0],f[i],f[i+1]]){if(!v[j])throw Error('Invalid OBJ face index.');t.push(...v[j]);}}}return t;}
function parseSTL(ab){const v=new DataView(ab),t=[];if(ab.byteLength>=84&&84+v.getUint32(80,true)*50===ab.byteLength){const n=v.getUint32(80,true);for(let i=0;i<n;i++)for(let j=0;j<9;j++)t.push(v.getFloat32(84+i*50+12+j*4,true));}else{const text=new TextDecoder().decode(ab);for(const m of text.matchAll(/vertex\s+([-+\deE.]+)\s+([-+\deE.]+)\s+([-+\deE.]+)/g))t.push(+m[1],+m[2],+m[3]);}return t;}
async function importFile(file){if(!file)return;const ext=file.name.split('.').pop().toLowerCase();if(!['blend','obj','stl'].includes(ext)){toast('Choose a .blend, .obj or .stl file.');return;}if(file.size>150*1024*1024){toast('File exceeds the 150 MB import limit.');return;}$('uploadBtn').disabled=true;toast('Reading '+file.name+'…',95000);try{let t,p=null,names=[];if(ext==='blend'){if(location.protocol==='file:')throw Error('Use the included Start Flow Lab launcher to enable Blender import.');const res=await fetch('/api/blend',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:file});const data=await res.json();if(!res.ok)throw Error(data.error||'Blender import failed.');t=data.triangles;p=data.parts;names=data.names;}else{const ab=await file.arrayBuffer();t=ext==='obj'?parseOBJ(new TextDecoder().decode(ab)):parseSTL(ab);}if(!t||t.length<9||t.length%9||t.some(x=>!Number.isFinite(x)))throw Error('No valid triangles were found in this file.');if(t.length/9>250000)throw Error('Mesh exceeds 250,000 triangles. Simplify it in Blender first.');let min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<t.length;i++){min[i%3]=Math.min(min[i%3],t[i]);max[i%3]=Math.max(max[i%3],t[i]);}if(Math.max(...max.map((x,i)=>x-min[i]))<1e-9)throw Error('The mesh has zero size.');meshSource=new Float32Array(t);parts=p;state.sphere=false;resetOrientationState();$('objectTitle').textContent='Flow around '+file.name.replace(/\.[^.]+$/,'');$('objectDetail').textContent=`${(t.length/9).toLocaleString()} triangles · evaluated solid geometry`;$('meshLabel').textContent=file.name;$('sizeValue').textContent=state.size.toFixed(2)+' m';initSolver();toast(`Loaded ${file.name}${names.length>1?' · '+names.length+' objects':''}. Solving the new boundary…`,6500);}catch(e){toast(e.message,13000);}finally{$('uploadBtn').disabled=false;$('fileInput').value='';}}
$('uploadBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>importFile(e.target.files[0]);$('sphereBtn').onclick=()=>{meshSource=null;parts=null;state.sphere=true;resetOrientationState();$('objectTitle').textContent='Flow around a sphere';$('objectDetail').textContent='Incompressible, viscous flow · no-slip surface';$('meshLabel').textContent='Sphere · analytic surface';initSolver();};let dragDepth=0;window.addEventListener('dragenter',e=>{e.preventDefault();dragDepth++;document.body.classList.add('dragging');});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('dragleave',e=>{e.preventDefault();if(--dragDepth<=0){dragDepth=0;document.body.classList.remove('dragging');}});window.addEventListener('drop',e=>{e.preventDefault();dragDepth=0;document.body.classList.remove('dragging');importFile(e.dataTransfer.files[0]);});
// Deterministic, read-only diagnostics for reproducible QA and physical sanity checks.
window.flowLab={get state(){return {...state};},get diagnostics(){return {...metadata,sceneRevision:initToken,orientationPending:orientation.pending,time:solverTime,displayTime:simTime,steps:solverSteps,fieldFinite:field?field.every(Number.isFinite):null,streamVertices:streamCount};},sample:(x,y,z)=>Array.from(sample(x,y,z)),get camera(){return {...camera,target:camera.target.slice()};},get orientation(){return {quaternion:orientation.q.slice(),angles:orientation.angles.slice(),forward:modelForward(),reference:orientation.reference,dragMode:orientation.mode,pending:orientation.pending};},solidAt:(x,y,z)=>{const i=Math.floor((x+6)/dx),j=Math.floor((y+4)/dx),k=Math.floor((z+4)/dx);return !!mask&&i>=0&&i<nx&&j>=0&&j<ny&&k>=0&&k<nz&&mask[i+nx*(j+ny*k)]===3;},get solidCells(){return mask?mask.reduce((a,b)=>a+(b===3),0):0;}};
bindOrientationControls();buildDomain();updateLegend();initSolver();requestAnimationFrame(render);
